version: "3"

services:
  mongo0:
    image: mongo:latest
    hostname: mongo0
    ports:
      - 37017:37017
    command: mongod --replSet tiny --port 37017
    depends_on:
        - mongo1
        - mongo2

  mongo1:
    image: mongo:latest
    hostname: mongo1
    ports:
      - 37018:37018
    command: mongod --replSet tiny --port 37018

  mongo2:
    image: mongo:latest
    hostname: mongo2
    ports:
      - 37019:37019
    command: mongod --replSet tiny --port 37019
